updated workflow file

diff --git a/.github/workflows/packerImage.yml b/.github/workflows/packerImage.yml
--- a/.github/workflows/packerImage.yml
+++ b/.github/workflows/packerImage.yml
@@ -1,46 +1,45 @@
-name : packerImage Build
+name: packerImage Build
 
 on:
-    push:
-      branches:
-        - main 
-    workflow_dispatch:
-  
+  pull_request:
+    branches:
+      - main
+  workflow_dispatch:
+
 jobs:
- test:
-    if: github.repository == 'CSYE-Preyash-002291343/webapp'
+  test:
     runs-on: ubuntu-latest
-  
+
     steps:
       - name: Install PostgreSQL
         run: |
           sudo apt-get update
           sudo apt-get install -y postgresql postgresql-client
-  
+
       - name: Start PostgreSQL service
         run: |
           sudo systemctl start postgresql.service
           sudo systemctl enable postgresql.service
           sudo systemctl status postgresql.service
-  
+
       - name: Wait for PostgreSQL to be ready
         run: until pg_isready -h localhost -p 5432; do sleep 3; done
-  
+
       - name: Create PostgreSQL user and database
         run: |
           sudo -u postgres psql -c "CREATE USER runner WITH SUPERUSER CREATEDB PASSWORD '${{ secrets.DB_PASS }}';"
           sudo -u postgres createdb ${{ secrets.DB_NAME }}
-      
+
       - uses: actions/checkout@v2
-  
+
       - name: Setup NodeJS Environment
         uses: actions/setup-node@v3
         with:
-          node-version: '20.14.0'
-  
+          node-version: "20.14.0"
+
       - name: Install dependencies
         run: npm install
-  
+
       - name: Run tests
         env:
           DB_USER: ${{ secrets.DB_USER_GITHUB }}
@@ -50,9 +49,8 @@ jobs:
           DB_PORT: 5432
         run: npm run test:DB -- --forceExit
 
-#pack the webapp and create .env file and build the packer image
- packer:
-    if: github.repository == 'CSYE-Preyash-002291343/webapp'
+  #pack the webapp and create .env file and build the packer image
+  packer:
     runs-on: ubuntu-latest
 
     steps:
@@ -63,7 +61,7 @@ jobs:
         run: |
           cd ..
           tar -czvf webapp.tar.gz webapp
-        
+
       - name: AWS Credential Setup
         uses: aws-actions/configure-aws-credentials@v1
         with:
@@ -81,3 +79,60 @@ jobs:
           cd packer/
           packer init .        
           packer build -var 'Port=${{ secrets.PORT }}' -var 'db_user=${{ secrets.DB_USER }}' -var 'db_pass=${{ secrets.DB_PASS }}' -var 'db_name=${{ secrets.DB_NAME }}' -var 'amiUsers=${{ secrets.AWS_USER}}' -var 'aws_region=${{vars.REGION}}' -var 'source_ami=${{vars.AMI}}' -var 'subnet_id=${{vars.SUBNET}}' aws.pkr.hcl
+          echo "AMI_ID=$AMI_ID" >> $GITHUB_ENV
+
+      - name: Create New Launch Template Version
+        run: |
+          echo "Fetching Latest Template ID"
+          TEMPLATE_ID=$(aws ec2 describe-launch-templates \
+            --filters "Name=launch-template-name,Values=${{ vars.LAUNCH_TEMPLATE_NAME }}" \
+            --query 'LaunchTemplates[0].LaunchTemplateId' \
+            --output text)
+
+          echo "Fetched Template ID: $TEMPLATE_ID"
+          echo "TEMPLATE_ID=$TEMPLATE_ID" >> $GITHUB_ENV
+
+          echo "Creating New Launch Template Version"
+          NEW_VERSION=$(aws ec2 create-launch-template-version \
+            --launch-template-id $TEMPLATE_ID \
+            --source-version $LATEST \
+            --launch-template-data "{\"ImageId\":\"${AMI_ID}\"}" \
+            --query 'LaunchTemplateVersion.VersionNumber' \
+            --output text)
+
+          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_ENV
+
+      - name: Update Auto Scaling Group to Use Latest Launch Template Version
+        run: |
+          aws autoscaling update-auto-scaling-group \
+            --auto-scaling-group-name ${{ vars.ASG_NAME }} \
+            --launch-template "LaunchTemplateId=${TEMPLATE_ID},Version=$NEW_VERSION"
+
+      - name: Start Instance Refresh
+        run: |
+          REFRESH_ID=$(aws autoscaling start-instance-refresh \
+            --auto-scaling-group-name ${{ vars.ASG_NAME }} \
+            --query 'InstanceRefreshId' \
+            --output text)
+
+          echo "Instance Refresh Started with ID: $REFRESH_ID"
+          echo "REFRESH_ID=$REFRESH_ID" >> $GITHUB_ENV
+
+      - name: Wait for Instance Refresh
+        run: |
+          while true; do
+            STATUS=$(aws autoscaling describe-instance-refreshes \
+              --auto-scaling-group-name ${{ vars.ASG_NAME }} \
+              --query 'InstanceRefreshes[0].Status' \
+              --output text)
+              
+            echo "Refresh Status: $STATUS"
+            if [[ "$STATUS" == "Successful" ]]; then
+              echo "Instance Refresh Completed Successfully."
+              exit 0
+            elif [[ "$STATUS" == "Failed" ]]; then
+              echo "Instance Refresh Failed."
+              exit 1
+            fi
+            sleep 30
+          done
